apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.database.url }}
  DB_HOST: {{ .Values.database.host }}
  DB_PORT: {{ .Values.database.port | quote }}
  DB_USER: {{ .Values.database.user }}
  DB_PASSWORD: {{ .Values.database.password }}
  DB_NAME: {{ .Values.database.name }}
